server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /pichu

management:
  endpoints:
    web:
      base-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    property-naming-strategy: SNAKE_CASE